### ISSUE TITLE
Issues with markdown

### ISSUE THREAD

**Issue by tami5** [cheap-glitch/vim-v#2]
Hey @cheap-glitch , great job on this, the quality of the plugin is amazing. Thanks a lot.

 After installation and enabling vlang g:markdown_fenced_languages, syntax highlight of markdown file breaks with no syntax highlighting 

```vim
let g:markdown_fenced_languages = [
      \ "html",
      \ "viml=vim",
      \ "go",
      \ "lua",
      \ "v",
      \ "vlang",
      \ "bash=sh",
      \ "clj=clojure",
      \ "js=javascript",
      \ "ruby",
      \]

```

I have a lot of markdown blocks with vlang, so it would be awesome to not have to change them. Also is it okay that I manually downloaded vim-v and add it to my pack start path

Thanks

**Comment by cheap-glitch** [comment]
Thank you for the kind words!

So if I understand right you're using some plugin to highlight Markdown and you want vlang blocks to be highlighted with `vim-v`? I'll need to know what plugin(s) you're using first and I'll see if I can do something about it.

> Also is it okay that I manually downloaded vim-v and add it to my pack start path

Sure, but I recommend using a plugin manager like [vim-plug](https://github.com/junegunn/vim-plug#readme), it's very easy to install a makes life much easier.

**Comment by tami5** [comment]
hey @cheap-glitch , It only breaks when I add vlang to the list. v works okay with no issue. as I used to v-vim before thats why I had vlang on the list. So long story short, can you support vlang as an addition to v, so that new users coming from v-vim will not have to change much when switch. Makes sense?

**Comment by cheap-glitch** [comment]
I pushed a fix to the main branch, tell me if that solves your problem.

**Comment by tami5** [comment]
Hey @cheap-glitch Thanks a lot, it sadily didn't. I think that it looks for syntax file with vlang.vim. Do you think its better to follow vim-v convention of defining v file type as vlang? it would be less confusing to do the same, don't you think?

Also I noticed that I can comment one lines with `//` instead of `*/ */` like v-vim. sry this is for another issue

**Comment by cheap-glitch** [comment]
> I think that it looks for syntax file with vlang.vim. Do you think its better to follow vim-v convention of defining v file type as vlang? it would be less confusing to do the same, don't you think?

That's what the fix is for. Did you make sure to use the latest version? When opening a `.v` file the command `:set filetype?` should print `vlang`.

> Also I noticed that I can comment one lines with // instead of */ */ like v-vim. sry this is for another issue

Indeed, please open a new issue for this.

**Comment by tami5** [comment]
> That's what the fix is for. Did you make sure to use the latest version? When opening a .v file the command :set filetype? should print vlang.

It prints v, I'm on `6ea4c41bfa3d0a20d60cfaf022c3ef41751b8862`

**Comment by cheap-glitch** [comment]
Maybe there's something wrong with your installation process? Did you try installing the plugin using `vim-plug`?
Also, what's the name of the plugin you use to highlight Markdown?

**Comment by tami5** [comment]
Its https://github.com/tpope/vim-markdown 

Yes I think it might be related to my installation process, Not sure if I can test it now with vim-plug.

**Comment by tami5** [comment]
hmmmmm thats wired just had some conflict. @cheap-glitch the issue is solved. Sorry for the wrong assessment. Thanks a lot.
