### ISSUE TITLE
Issues with single line comments

### ISSUE THREAD

**Issue by tami5** [cheap-glitch/vim-v#3]
Hey @cheap-glitch 

I'm using `tpope/vim-commentary` and when i do gcc, instead of online comment `//` the line get wrapped with `/* */` 

Thanks

**Comment by cheap-glitch** [comment]
See https://github.com/tpope/vim-commentary#faq

**Comment by tami5** [comment]
Thanks a lot, it just wired it didn't respond to what you've added in vim-v ftplugin. 
Adding `setlocal commentstring=//\ %s` to `after/ftplugin/vlang.vim` fixed my issue

Thanks again :heart:
